export interface Property {
    id: string;
    title: string;
    description?: string;
    price: number;
    location: string;
    type: 'Rumah' | 'Ruko' | 'Gudang' | 'Kavling';
    bedrooms?: number;
    bathrooms?: number;
    area: number; // m2
    image: string;
    seller: {
        name: string;
        avatar: string;
        verified: boolean;
    };
    rating: number;
}

export const MOCK_PROPERTIES: Property[] = [
    // RUMAH
    {
        id: '1',
        title: 'Rumah Modern Minimalis di BSD City',
        description: 'Hunian nyaman dengan desain minimalis modern, lingkungan asri, dan keamanan 24 jam.',
        price: 2500000000,
        location: 'BSD City, Tangerang Selatan',
        type: 'Rumah',
        bedrooms: 3,
        bathrooms: 2,
        area: 120,
        image: 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&q=80&w=800',
        seller: { name: 'Budi Santoso', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Budi', verified: true },
        rating: 4.8,
    },
    {
        id: '4',
        title: 'Rumah Asri Nuansa Bali',
        description: 'Rumah dengan konsep villa Bali yang menenangkan, dilengkapi taman tropis.',
        price: 4200000000,
        location: 'Ubud, Gianyar',
        type: 'Rumah',
        bedrooms: 4,
        bathrooms: 3,
        area: 250,
        image: 'https://images.unsplash.com/photo-1583608205776-bfd35f0d9f83?auto=format&fit=crop&q=80&w=800',
        seller: { name: 'Made Artha', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Made', verified: true },
        rating: 5.0,
    },
    {
        id: '6',
        title: 'Rumah Keluarga Halaman Luas',
        description: 'Rumah ideal untuk keluarga besar dengan halaman belakang yang luas untuk bermain anak.',
        price: 1200000000,
        location: 'Bogor, Jawa Barat',
        type: 'Rumah',
        bedrooms: 3,
        bathrooms: 2,
        area: 100,
        image: 'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?auto=format&fit=crop&q=80&w=800',
        seller: { name: 'Ahmad Dani', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Ahmad', verified: true },
        rating: 4.7,
    },
    {
        id: '7',
        title: 'Cluster Elite Pondok Indah',
        description: 'Hunian prestisius di lokasi paling strategis Jakarta Selatan.',
        price: 15000000000,
        location: 'Pondok Indah, Jakarta Selatan',
        type: 'Rumah',
        bedrooms: 5,
        bathrooms: 6,
        area: 600,
        image: 'https://images.unsplash.com/photo-1600596542815-e32c8cc13bc9?auto=format&fit=crop&q=80&w=800',
        seller: { name: 'Jessica Tan', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Jessica', verified: true },
        rating: 4.9,
    },
    {
        id: '8',
        title: 'Rumah Scandinavia Bandung',
        description: 'Desain Scandinavian yang cozy dengan udara sejuk Bandung Utara.',
        price: 1850000000,
        location: 'Dago, Bandung',
        type: 'Rumah',
        bedrooms: 3,
        bathrooms: 2,
        area: 110,
        image: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&q=80&w=800',
        seller: { name: 'Dedi Kurniawan', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Dedi', verified: false },
        rating: 4.6,
    },
    {
        id: '9',
        title: 'Townhouse Kemang Modern',
        description: 'Townhouse eksklusif dengan private pool dan rooftop garden.',
        price: 5500000000,
        location: 'Kemang, Jakarta Selatan',
        type: 'Rumah',
        bedrooms: 4,
        bathrooms: 4,
        area: 220,
        image: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&q=80&w=800',
        seller: { name: 'Maya Putri', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Maya', verified: true },
        rating: 4.8,
    },
    {
        id: '10',
        title: 'Rumah Subsidi Berkualitas',
        description: 'Rumah subsidi dengan kualitas bangunan prima, lokasi berkembang.',
        price: 180000000,
        location: 'Cikarang, Bekasi',
        type: 'Rumah',
        bedrooms: 2,
        bathrooms: 1,
        area: 36,
        image: 'https://images.unsplash.com/photo-1568605114967-8130f3a36994?auto=format&fit=crop&q=80&w=800',
        seller: { name: 'PT Bangun Sejahtera', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Bangun', verified: true },
        rating: 4.2,
    },
    {
        id: '26',
        title: 'Rumah Hook Posisi Strategis',
        description: 'Rumah posisi hook dengan sirkulasi udara sangat baik.',
        price: 2100000000,
        location: 'Harapan Indah, Bekasi',
        type: 'Rumah',
        bedrooms: 4,
        bathrooms: 3,
        area: 180,
        image: 'https://images.unsplash.com/photo-1605276374104-dee2a0ed3cd6?auto=format&fit=crop&q=80&w=800',
        seller: { name: 'Rudy Hartono', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Rudy', verified: true },
        rating: 4.5,
    },

    // RUKO
    {
        id: '3',
        title: 'Ruko Strategis Pinggir Jalan',
        description: 'Ruko 3 lantai di lokasi sangat strategis, pinggir jalan raya utama.',
        price: 3500000000,
        location: 'Kelapa Gading, Jakarta Utara',
        type: 'Ruko',
        bedrooms: 2,
        bathrooms: 2,
        area: 150,
        image: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&q=80&w=800',
        seller: { name: 'Properti Indo', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Indo', verified: true },
        rating: 4.5,
    },
    {
        id: '11',
        title: 'Ruko Grand Wisata',
        description: 'Ruko baru cocok untuk kantor atau usaha kuliner.',
        price: 2800000000,
        location: 'Grand Wisata, Bekasi',
        type: 'Ruko',
        bedrooms: 0,
        bathrooms: 2,
        area: 130,
        image: 'https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&q=80&w=800',
        seller: { name: 'Sentosa Property', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Sentosa', verified: true },
        rating: 4.4,
    },
    {
        id: '12',
        title: 'Shophouse PIK 2',
        description: 'Kawasan komersial paling hits di Jakarta Utara dengan view laut.',
        price: 6500000000,
        location: 'PIK 2, Jakarta Utara',
        type: 'Ruko',
        bedrooms: 0,
        bathrooms: 3,
        area: 250,
        image: 'https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?auto=format&fit=crop&q=80&w=800',
        seller: { name: 'PIK Marketing', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=PIK', verified: true },
        rating: 4.9,
    },
    {
        id: '13',
        title: 'Ruko Pasar Modern',
        description: 'Sangat cocok untuk usaha retail, trafik pengunjung tinggi.',
        price: 1500000000,
        location: 'Bintaro, Tangerang Selatan',
        type: 'Ruko',
        bedrooms: 0,
        bathrooms: 1,
        area: 90,
        image: 'https://images.unsplash.com/photo-1555636222-cae831e670b3?auto=format&fit=crop&q=80&w=800',
        seller: { name: 'Haji Dul', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Dul', verified: false },
        rating: 4.3,
    },
    {
        id: '14',
        title: 'Ruko 4 Lantai Jakarta Barat',
        description: 'Siap pakai, bekas kantor bank, keamanan terjamin.',
        price: 8000000000,
        location: 'Puri Indah, Jakarta Barat',
        type: 'Ruko',
        bedrooms: 0,
        bathrooms: 4,
        area: 300,
        image: 'https://images.unsplash.com/photo-1577495508048-b635879837f1?auto=format&fit=crop&q=80&w=800',
        seller: { name: 'Bank Central', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Bank', verified: true },
        rating: 4.6,
    },
    {
        id: '27',
        title: 'Ruko 2 Lantai Minimalis',
        description: 'Cocok untuk start-up atau cafe kecil.',
        price: 1900000000,
        location: 'Serpong, Tangerang',
        type: 'Ruko',
        bedrooms: 1,
        bathrooms: 2,
        area: 100,
        image: 'https://images.unsplash.com/photo-1519710164239-da123dc03ef4?auto=format&fit=crop&q=80&w=800',
        seller: { name: 'Kevin Sanjaya', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Kevin', verified: true },
        rating: 4.4,
    },

    // GUDANG
    {
        id: '15',
        title: 'Gudang Modern Delta Silicon',
        description: 'Gudang standar internasional, akses kontainer 40ft mudah.',
        price: 12000000000,
        location: 'Cikarang, Bekasi',
        type: 'Gudang',
        bedrooms: 0,
        bathrooms: 2,
        area: 1000,
        image: 'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?auto=format&fit=crop&q=80&w=800',
        seller: { name: 'Industrial Estate', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Industrial', verified: true },
        rating: 4.7,
    },
    {
        id: '16',
        title: 'Gudang Logistik Karawang',
        description: 'Dekat pintu tol, bebas banjir, lantai beton bertulang.',
        price: 25000000000,
        location: 'Karawang Barat',
        type: 'Gudang',
        bedrooms: 0,
        bathrooms: 4,
        area: 2500,
        image: 'https://images.unsplash.com/photo-1553413077-190dd305871c?auto=format&fit=crop&q=80&w=800',
        seller: { name: 'Logistik Maju', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Logistik', verified: true },
        rating: 4.8,
    },
    {
        id: '17',
        title: 'Gudang Kecil Bizpark',
        description: 'Cocok untuk penyimpanan barang online shop atau distributor kecil.',
        price: 3500000000,
        location: 'Pulogadung, Jakarta Timur',
        type: 'Gudang',
        bedrooms: 0,
        bathrooms: 1,
        area: 300,
        image: 'https://images.unsplash.com/photo-1473642131507-60b38323c9ce?auto=format&fit=crop&q=80&w=800',
        seller: { name: 'Bizpark Owner', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Biz', verified: false },
        rating: 4.5,
    },
    {
        id: '18',
        title: 'Gudang Pendingin (Cold Storage)',
        description: 'Fasilitas cold storage lengkap, suhu bisa diatur minus.',
        price: 18000000000,
        location: 'Tanjung Priok, Jakarta Utara',
        type: 'Gudang',
        bedrooms: 0,
        bathrooms: 2,
        area: 800,
        image: 'https://images.unsplash.com/photo-1587293852726-70cdb56c2866?auto=format&fit=crop&q=80&w=800',
        seller: { name: 'Seafood Export', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Sea', verified: true },
        rating: 4.9,
    },
    {
        id: '28',
        title: 'Gudang Siap Pakai Sidoarjo',
        description: 'Komplek pergudangan aman 24 jam.',
        price: 5000000000,
        location: 'Sidoarjo, Jawa Timur',
        type: 'Gudang',
        bedrooms: 0,
        bathrooms: 1,
        area: 500,
        image: 'https://images.unsplash.com/photo-1590247813693-5541d1c609fd?auto=format&fit=crop&q=80&w=800',
        seller: { name: 'Jatim Properti', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Jatim', verified: true },
        rating: 4.6,
    },

    // KAVLING
    {
        id: '19',
        title: 'Kavling Siap Bangun Sentul',
        description: 'Tanah kavling dengan view gunung Salak, udara sejuk.',
        price: 900000000,
        location: 'Sentul City, Bogor',
        type: 'Kavling',
        bedrooms: 0,
        bathrooms: 0,
        area: 200,
        image: 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&q=80&w=800',
        seller: { name: 'Sentul Realty', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Sentul', verified: true },
        rating: 4.7,
    },
    {
        id: '20',
        title: 'Tanah Komersial TB Simatupang',
        description: 'Lokasi premium di area perkantoran, cocok untuk gedung tinggi.',
        price: 85000000000,
        location: 'TB Simatupang, Jakarta Selatan',
        type: 'Kavling',
        bedrooms: 0,
        bathrooms: 0,
        area: 2000,
        image: 'https://images.unsplash.com/photo-1464295325992-d59bd844dbfa?auto=format&fit=crop&q=80&w=800',
        seller: { name: 'Land Owner', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Land', verified: true },
        rating: 5.0,
    },
    {
        id: '21',
        title: 'Kavling Villa Puncak',
        description: 'Tanah luas cocok untuk villa peristirahatan keluarga.',
        price: 1500000000,
        location: 'Cisarua, Puncak',
        type: 'Kavling',
        bedrooms: 0,
        bathrooms: 0,
        area: 1000,
        image: 'https://images.unsplash.com/photo-1449844908441-8829872d2607?auto=format&fit=crop&q=80&w=800',
        seller: { name: 'Pak Haji Asep', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Asep', verified: false },
        rating: 4.4,
    },
    {
        id: '22',
        title: 'Tanah Industri Kendal',
        description: 'Dalam kawasan industri terpadu Kendal, Jawa Tengah.',
        price: 15000000000,
        location: 'Kendal, Jawa Tengah',
        type: 'Kavling',
        bedrooms: 0,
        bathrooms: 0,
        area: 5000,
        image: 'https://images.unsplash.com/photo-1533552755457-580746401062?auto=format&fit=crop&q=80&w=800',
        seller: { name: 'Kendal Industrial', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Kendal', verified: true },
        rating: 4.6,
    },
    {
        id: '23',
        title: 'Kavling Hoek Menteng',
        description: 'Jarang ada! Kavling hoek di kawasan elite Menteng.',
        price: 120000000000,
        location: 'Menteng, Jakarta Pusat',
        type: 'Kavling',
        bedrooms: 0,
        bathrooms: 0,
        area: 800,
        image: 'https://images.unsplash.com/photo-1516156008625-3a9d6067fab5?auto=format&fit=crop&q=80&w=800',
        seller: { name: 'Luxury Land', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Luxury', verified: true },
        rating: 5.0,
    },
    {
        id: '24',
        title: 'Tanah Strategis Jogja',
        description: 'Dekat kampus UGM, cocok untuk kost eksklusif.',
        price: 3500000000,
        location: 'Sleman, Yogyakarta',
        type: 'Kavling',
        bedrooms: 0,
        bathrooms: 0,
        area: 300,
        image: 'https://images.unsplash.com/photo-1528659556209-5d465d63f25c?auto=format&fit=crop&q=80&w=800',
        seller: { name: 'Mas Joko', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Joko', verified: true },
        rating: 4.8,
    },
    {
        id: '25',
        title: 'Kavling Resort Bali',
        description: 'Tanah cliff front dengan view laut abadi di Uluwatu.',
        price: 45000000000,
        location: 'Uluwatu, Bali',
        type: 'Kavling',
        bedrooms: 0,
        bathrooms: 0,
        area: 1500,
        image: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&q=80&w=800',
        seller: { name: 'Bali Property', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Bali', verified: true },
        rating: 5.0,
    },
    {
        id: '29',
        title: 'Rumah Mewah Pondok Indah',
        description: 'Rumah mewah dengan kolam renang pribadi dan taman luas.',
        price: 25000000000,
        location: 'Pondok Indah, Jakarta Selatan',
        type: 'Rumah',
        bedrooms: 5,
        bathrooms: 6,
        area: 800,
        image: 'https://images.unsplash.com/photo-1600596542815-e32c8cc13bc9?auto=format&fit=crop&q=80&w=800',
        seller: { name: 'Luxury Homes', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=LuxuryHomes', verified: true },
        rating: 5.0,
    },
    {
        id: '30',
        title: 'Apartemen Green Bay Pluit',
        description: 'Apartemen dengan view laut dan akses langsung ke mall.',
        price: 800000000,
        location: 'Pluit, Jakarta Utara',
        type: 'Kavling', // Changed to Kavling as Apartemen is removed, or should be Ruko? User asked for 30 items, maybe I should just use the supported types. Let's make it Kavling/Tanah or skip apartment. Ah, apartemen is removed.
        bedrooms: 2,
        bathrooms: 1,
        area: 45,
        image: 'https://images.unsplash.com/photo-1570129477492-45f003f2dffa?auto=format&fit=crop&q=80&w=800',
        seller: { name: 'Green Bay Marketing', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=GreenBay', verified: true },
        rating: 4.5,
    }
];
