
export interface BlogPost {
    id: number;
    title: string;
    excerpt: string;
    category: string;
    author: string;
    date: string;
    readTime: string;
    imageUrl: string;
    authorAvatar: string;
    authorTitle?: string;
}

export const MOCK_BLOG_POSTS: BlogPost[] = [
    {
        id: 1,
        title: "Tren Properti 2026: Hunian Ramah Lingkungan Semakin Diminati",
        excerpt: "Mengapa properti dengan konsep eco-living menjadi incaran milenal dan investor di tahun ini? Simak analisis lengkapnya.",
        category: "Tren Pasar",
        author: "Sarah Wijaya",
        authorTitle: "Senior Analyst",
        date: "10 Jan 2024",
        readTime: "5 min baca",
        imageUrl: "https://images.unsplash.com/photo-1518780664697-55e3ad937233?auto=format&fit=crop&q=80&w=1200",
        authorAvatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&q=80&w=150"
    },
    {
        id: 2,
        title: "Tips Membeli Rumah Pertama dengan Gaji UMR, Apakah Bisa?",
        excerpt: "Panduan lengkap mengatur keuangan dan memilih KPR yang tepat untuk mewujudkan impian punya rumah sendiri.",
        category: "Tips & Trik",
        author: "Budi Santoso",
        authorTitle: "Financial Planner",
        date: "08 Jan 2024",
        readTime: "7 min baca",
        imageUrl: "https://images.unsplash.com/photo-1560518883-ce09059eeffa?auto=format&fit=crop&q=80&w=1200",
        authorAvatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&q=80&w=150"
    },
    {
        id: 3,
        title: "5 Wilayah di Jabodetabek dengan Kenaikan Harga Properti Tertinggi",
        excerpt: "Data terbaru menunjukkan pergeseran minat ke wilayah penyangga. Cek apakah daerah incaranmu termasuk!",
        category: "Investasi",
        author: "Diana Putri",
        authorTitle: "Real Estate Expert",
        date: "05 Jan 2024",
        readTime: "4 min baca",
        imageUrl: "https://images.unsplash.com/photo-1448630360428-65456885c650?auto=format&fit=crop&q=80&w=1200",
        authorAvatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=150"
    },
    {
        id: 4,
        title: "Desain Interior Minimalis Modern untuk Apartemen Studio",
        excerpt: "Maksimalkan ruang terbatas dengan hacks desain interior yang cerdas dan estetik ala Skandinavia.",
        category: "Desain",
        author: "Rendi Pratama",
        authorTitle: "Interior Designer",
        date: "03 Jan 2024",
        readTime: "6 min baca",
        imageUrl: "https://images.unsplash.com/photo-1502005229762-cf1afd38088d?auto=format&fit=crop&q=80&w=1200",
        authorAvatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=150"
    },
    {
        id: 5,
        title: "Panduan Lengkap Pajak Jual Beli Properti yang Wajib Diketahui",
        excerpt: "Jangan sampai bingung! Pelajari jenis-jenis pajak yang timbul saat transaksi properti agar tidak salah hitung.",
        category: "Hukum & Legal",
        author: "Maya Indah",
        authorTitle: "Legal Consultant",
        date: "28 Des 2023",
        readTime: "8 min baca",
        imageUrl: "https://images.unsplash.com/photo-1554224155-8d04cb21cd6c?auto=format&fit=crop&q=80&w=1200",
        authorAvatar: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&q=80&w=150"
    },
    {
        id: 6,
        title: "Mengenal Smart Home System: Kemewahan atau Kebutuhan?",
        excerpt: "Teknologi rumah pintar semakin terjangkau. Ketahui manfaat dan biaya instalasi untuk rumah masa depanmu.",
        category: "Teknologi",
        author: "Ari Wibowo",
        authorTitle: "Tech Specialist",
        date: "25 Des 2023",
        readTime: "5 min baca",
        imageUrl: "https://images.unsplash.com/photo-1558002038-1091a1661116?auto=format&fit=crop&q=80&w=1200",
        authorAvatar: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&q=80&w=150"
    },
    {
        id: 7,
        title: "Masa Depan Co-living di Jakarta: Solusi Hunian Milenial",
        excerpt: "Fenomena co-living terus berkembang. Apakah ini investasi masa depan yang menjanjikan?",
        category: "Tren Pasar",
        author: "Sarah Wijaya",
        authorTitle: "Senior Analyst",
        date: "20 Des 2023",
        readTime: "6 min baca",
        imageUrl: "https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?auto=format&fit=crop&q=80&w=1200",
        authorAvatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&q=80&w=150"
    },
    {
        id: 8,
        title: "7 Kesalahan Fatal Saat Membeli Tanah Kavling",
        excerpt: "Pastikan tanah yang Anda beli aman secara legalitas. Hindari kesalahan umum berikut ini.",
        category: "Tips & Trik",
        author: "Maya Indah",
        authorTitle: "Legal Consultant",
        date: "15 Des 2023",
        readTime: "10 min baca",
        imageUrl: "https://images.unsplash.com/photo-1500382017468-9049fee74a62?auto=format&fit=crop&q=80&w=1200",
        authorAvatar: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&q=80&w=150"
    },
    {
        id: 9,
        title: "Manfaat Biophilic Design: Membawa Alam ke Dalam Rumah",
        excerpt: "Meningkatkan kesehatan mental dengan elemen alam dalam interior rumah modern.",
        category: "Desain",
        author: "Rendi Pratama",
        authorTitle: "Interior Designer",
        date: "12 Des 2023",
        readTime: "5 min baca",
        imageUrl: "https://images.unsplash.com/photo-1513519245088-0e12902e35ca?auto=format&fit=crop&q=80&w=1200",
        authorAvatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=150"
    },
    {
        id: 10,
        title: "Analisis Pasar Properti Pasca Pemilu 2024",
        excerpt: "Bagaimana kondisi ekonomi politik mempengaruhi minat beli properti di tahun politik?",
        category: "Tren Pasar",
        author: "Diana Putri",
        authorTitle: "Real Estate Expert",
        date: "10 Des 2023",
        readTime: "8 min baca",
        imageUrl: "https://images.unsplash.com/photo-1526304640581-d334cdbbf5d7?auto=format&fit=crop&q=80&w=1200",
        authorAvatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=150"
    },
    {
        id: 11,
        title: "Investasi Properti di Kawasan Wisata: Untung atau Buntung?",
        excerpt: "Menilik potensi keuntungan sewa jangka pendek di destinasi wisata favorit Indonesia.",
        category: "Investasi",
        author: "Budi Santoso",
        authorTitle: "Financial Planner",
        date: "05 Des 2023",
        readTime: "7 min baca",
        imageUrl: "https://images.unsplash.com/photo-1510091622838-64bb170de94b?auto=format&fit=crop&q=80&w=1200",
        authorAvatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&q=80&w=150"
    },
    {
        id: 12,
        title: "Pemanfaatan AI dalam Pencarian Properti",
        excerpt: "Bagaimana algoritma cerdas membantu Anda menemukan rumah impian dengan lebih cepat.",
        category: "Teknologi",
        author: "Ari Wibowo",
        authorTitle: "Tech Specialist",
        date: "01 Des 2023",
        readTime: "4 min baca",
        imageUrl: "https://images.unsplash.com/photo-1485827404703-89b55fcc595e?auto=format&fit=crop&q=80&w=1200",
        authorAvatar: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&q=80&w=150"
    },
    {
        id: 13,
        title: "Etiket Hidup di Apartemen: Hal yang Wajib Dipatuhi",
        excerpt: "Panduan bertetangga yang baik dan aturan umum tinggal di hunian vertikal.",
        category: "Gaya Hidup",
        author: "Sarah Wijaya",
        authorTitle: "Community Manager",
        date: "28 Nov 2023",
        readTime: "5 min baca",
        imageUrl: "https://images.unsplash.com/photo-1493238792000-8113da705763?auto=format&fit=crop&q=80&w=1200",
        authorAvatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&q=80&w=150"
    },
    {
        id: 14,
        title: "Keuntungan Membeli Properti Off-plan",
        excerpt: "Mengapa membeli properti sebelum dibangun bisa memberikan ROI yang lebih tinggi.",
        category: "Investasi",
        author: "Diana Putri",
        authorTitle: "Real Estate Expert",
        date: "25 Nov 2023",
        readTime: "6 min baca",
        imageUrl: "https://images.unsplash.com/photo-1503387762-592deb58ef4e?auto=format&fit=crop&q=80&w=1200",
        authorAvatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=150"
    },
    {
        id: 15,
        title: "Cara Menghitung Nilai Jual Objek Pajak (NJOP)",
        excerpt: "Metode sederhana menentukan nilai properti Anda sesuai regulasi pemerintah.",
        category: "Hukum & Legal",
        author: "Maya Indah",
        authorTitle: "Legal Consultant",
        date: "20 Nov 2023",
        readTime: "7 min baca",
        imageUrl: "https://images.unsplash.com/photo-1450101499163-c8848c66ca85?auto=format&fit=crop&q=80&w=1200",
        authorAvatar: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&q=80&w=150"
    },
    {
        id: 16,
        title: "Review Properti: Cluster Premium di BSD City",
        excerpt: "Melihat lebih dekat fasilitas dan desain dari pengembangan properti tercanggih saat ini.",
        category: "Properti Baru",
        author: "Rendi Pratama",
        authorTitle: "Property Reviewer",
        date: "15 Nov 2023",
        readTime: "9 min baca",
        imageUrl: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&q=80&w=1200",
        authorAvatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=150"
    },
    {
        id: 17,
        title: "Investasi Emas vs Properti: Mana yang Lebih Menguntungkan?",
        excerpt: "Perbandingan mendalam profil risiko dan potensi cuan kedua instrumen investasi ini.",
        category: "Keuangan",
        author: "Budi Santoso",
        authorTitle: "Financial Planner",
        date: "10 Nov 2023",
        readTime: "8 min baca",
        imageUrl: "https://images.unsplash.com/photo-1584483766114-2cea6facdf57?auto=format&fit=crop&q=80&w=1200",
        authorAvatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&q=80&w=150"
    },
    {
        id: 18,
        title: "Trend Warna Cat Rumah 2026: Earthy Tones Kembali!",
        excerpt: "Wujudkan suasana tenang dan hangat di rumah dengan pilihan palet warna alam.",
        category: "Desain",
        author: "Sarah Wijaya",
        authorTitle: "Visual Stylist",
        date: "05 Nov 2023",
        readTime: "5 min baca",
        imageUrl: "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&q=80&w=1200",
        authorAvatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&q=80&w=150"
    },
    {
        id: 19,
        title: "Membangun Rumah Tahan Gempa: Spesifikasi dan Biaya",
        excerpt: "Pentingnya struktur bangunan yang aman bagi Anda yang tinggal di zona rawan gempa.",
        category: "Tips & Trik",
        author: "Ari Wibowo",
        authorTitle: "Technical Advisor",
        date: "01 Nov 2023",
        readTime: "12 min baca",
        imageUrl: "https://images.unsplash.com/photo-1541888946425-d81bb19480c5?auto=format&fit=crop&q=80&w=1200",
        authorAvatar: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&q=80&w=150"
    },
    {
        id: 20,
        title: "Gaya Hidup Minimalis: Decluttering untuk Rumah Lebih Luas",
        excerpt: "Tips menyortir barang agar hunian terasa lebih bernapas dan teratur.",
        category: "Gaya Hidup",
        author: "Diana Putri",
        authorTitle: "Expert Organizer",
        date: "28 Okt 2023",
        readTime: "6 min baca",
        imageUrl: "https://images.unsplash.com/photo-1581403341630-a6e0b9d2d295?auto=format&fit=crop&q=80&w=1200",
        authorAvatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=150"
    },
    {
        id: 21,
        title: "Digital Nomad: Mencari Hunian Ideal untuk Remote Work",
        excerpt: "Fasilitas apa saja yang wajib ada di rumah para pekerja digital masa kini?",
        category: "Gaya Hidup",
        author: "Ari Wibowo",
        authorTitle: "Technology Expert",
        date: "25 Okt 2023",
        readTime: "5 min baca",
        imageUrl: "https://images.unsplash.com/photo-1522202176988-66273c2fd55f?auto=format&fit=crop&q=80&w=1200",
        authorAvatar: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&q=80&w=150"
    },
    {
        id: 22,
        title: "Cara Klaim Asuransi Properti Saat Terjadi Bencana",
        excerpt: "Langkah demi langkah mengurus asuransi rumah agar proteksi Anda maksimal.",
        category: "Hukum & Legal",
        author: "Maya Indah",
        authorTitle: "Legal Consultant",
        date: "22 Okt 2023",
        readTime: "7 min baca",
        imageUrl: "https://images.unsplash.com/photo-1509017174183-0b7e0278f1ec?auto=format&fit=crop&q=80&w=1200",
        authorAvatar: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&q=80&w=150"
    },
    {
        id: 23,
        title: "Review Apartemen Luxury di Kawasan SCBD",
        excerpt: "Eksplorasi kemewahan tiada tara di jantung pusat bisnis Jakarta.",
        category: "Properti Baru",
        author: "Rendi Pratama",
        authorTitle: "Luxury Reviewer",
        date: "18 Okt 2023",
        readTime: "10 min baca",
        imageUrl: "https://images.unsplash.com/photo-1460317442991-0ec209397118?auto=format&fit=crop&q=80&w=1200",
        authorAvatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=150"
    },
    {
        id: 24,
        title: "Perencanaan Keuangan untuk Renovasi Rumah Impian",
        excerpt: "Cara mengatur budget agar renovasi tidak overbudget dan selesai tepat waktu.",
        category: "Keuangan",
        author: "Budi Santoso",
        authorTitle: "Financial Planner",
        date: "15 Okt 2023",
        readTime: "9 min baca",
        imageUrl: "https://images.unsplash.com/photo-1503387762-592deb58ef4e?auto=format&fit=crop&q=80&w=1200",
        authorAvatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&q=80&w=150"
    },
    {
        id: 25,
        title: "Trend Tanaman Indoor untuk Mempercantik Ruangan",
        excerpt: "Jenis tanaman yang mudah dirawat dan memberikan kesan segar di dalam rumah.",
        category: "Desain",
        author: "Sarah Wijaya",
        authorTitle: "Botanical Stylist",
        date: "12 Okt 2023",
        readTime: "4 min baca",
        imageUrl: "https://images.unsplash.com/photo-1485955900006-10f4d324d411?auto=format&fit=crop&q=80&w=1200",
        authorAvatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&q=80&w=150"
    },
    {
        id: 26,
        title: "Dampak Kenaikan Suku Bunga BI Terhadap Cicilan KPR",
        excerpt: "Strategi menghadapi cicilan bank yang naik bagi pemilik KPR floating rate.",
        category: "Investasi",
        author: "Diana Putri",
        authorTitle: "Real Estate Expert",
        date: "08 Okt 2023",
        readTime: "7 min baca",
        imageUrl: "https://images.unsplash.com/photo-1554224155-8d04cb21cd6c?auto=format&fit=crop&q=80&w=1200",
        authorAvatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=150"
    },
    {
        id: 27,
        title: "Mengenal Izin Mendirikan Bangunan (IMB) / PBG",
        excerpt: "Segala hal yang perlu Anda siapkan untuk mengurus perizinan bangunan terbaru.",
        category: "Hukum & Legal",
        author: "Maya Indah",
        authorTitle: "Legal Consultant",
        date: "05 Okt 2023",
        readTime: "8 min baca",
        imageUrl: "https://images.unsplash.com/photo-1589829545856-d10d557cf95f?auto=format&fit=crop&q=80&w=1200",
        authorAvatar: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&q=80&w=150"
    },
    {
        id: 28,
        title: "Teknologi Solar Panel untuk Rumah Tangga",
        excerpt: "Berapa modal awal dan seberapa besar penghematan listrik yang dihasilkan?",
        category: "Teknologi",
        author: "Ari Wibowo",
        authorTitle: "Sustainable Tech",
        date: "01 Okt 2023",
        readTime: "6 min baca",
        imageUrl: "https://images.unsplash.com/photo-1509391366360-fe5bb658582f?auto=format&fit=crop&q=80&w=1200",
        authorAvatar: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&q=80&w=150"
    },
    {
        id: 29,
        title: "Investasi Properti untuk Dana Pensiun",
        excerpt: "Mengapa properti menjadi pilihan aset favorit untuk menjamin masa tua yang nyaman.",
        category: "Keuangan",
        author: "Budi Santoso",
        authorTitle: "Financial Planner",
        date: "28 Sep 2023",
        readTime: "10 min baca",
        imageUrl: "https://images.unsplash.com/photo-1554469384-e58fac16e23a?auto=format&fit=crop&q=80&w=1200",
        authorAvatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&q=80&w=150"
    },
    {
        id: 30,
        title: "Rumah Konsep Open Space: Kelebihan dan Kekurangan",
        excerpt: "Tren desain tanpa sekat yang membuat rumah terasa lebih luas namun butuh perhatian khusus.",
        category: "Desain",
        author: "Rendi Pratama",
        authorTitle: "Interior Designer",
        date: "25 Sep 2023",
        readTime: "6 min baca",
        imageUrl: "https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?auto=format&fit=crop&q=80&w=1200",
        authorAvatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=150"
    },
    {
        id: 31,
        title: "Transit Oriented Development (TOD): Solusi Macet Jakarta",
        excerpt: "Mengenal konsep hunian yang terintegrasi langsung dengan transportasi publik.",
        category: "Tren Pasar",
        author: "Sarah Wijaya",
        authorTitle: "Senior Analyst",
        date: "20 Sep 2023",
        readTime: "7 min baca",
        imageUrl: "https://images.unsplash.com/photo-1449824913935-59a10b8d2000?auto=format&fit=crop&q=80&w=1200",
        authorAvatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&q=80&w=150"
    },
    {
        id: 32,
        title: "Hukum Waris Properti: Prosedur Balik Nama Sertifikat",
        excerpt: "Langkah legal yang harus ditempuh agar aset warisan sah secara hukum.",
        category: "Hukum & Legal",
        author: "Maya Indah",
        authorTitle: "Legal Consultant",
        date: "15 Sep 2023",
        readTime: "12 min baca",
        imageUrl: "https://images.unsplash.com/photo-1450101499163-c8848c66ca85?auto=format&fit=crop&q=80&w=1200",
        authorAvatar: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&q=80&w=150"
    },
    {
        id: 33,
        title: "Smart Lighting: Mengatur Mood Ruangan Lewat Smartphone",
        excerpt: "Transformasi pencahayaan rumah menjadi lebih dinamis dan hemat energi.",
        category: "Teknologi",
        author: "Ari Wibowo",
        authorTitle: "Tech Specialist",
        date: "10 Sep 2023",
        readTime: "5 min baca",
        imageUrl: "https://images.unsplash.com/photo-1550989460-0adf9ea622e2?auto=format&fit=crop&q=80&w=1200",
        authorAvatar: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&q=80&w=150"
    },
    {
        id: 34,
        title: "Konsep Kitchen Island untuk Dapur Lebih Fungsional",
        excerpt: "Inspirasi area dapur yang tidak hanya untuk memasak tapi juga tempat berkumpul.",
        category: "Desain",
        author: "Sarah Wijaya",
        authorTitle: "Interior Designer",
        date: "05 Sep 2023",
        readTime: "6 min baca",
        imageUrl: "https://images.unsplash.com/photo-1556911220-e15224bbafb0?auto=format&fit=crop&q=80&w=1200",
        authorAvatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&q=80&w=150"
    },
    {
        id: 35,
        title: "Perbandingan KPR Syariah dan KPR Konvensional",
        excerpt: "Memahami perbedaan margin dan bunga untuk menentukan skema yang tepat pas di hati.",
        category: "Keuangan",
        author: "Budi Santoso",
        authorTitle: "Financial Planner",
        date: "01 Sep 2023",
        readTime: "8 min baca",
        imageUrl: "https://images.unsplash.com/photo-1450101499163-c8848c66ca85?auto=format&fit=crop&q=80&w=1200",
        authorAvatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&q=80&w=150"
    },
    {
        id: 36,
        title: "Rumah Tumbuh: Konsep Membangun Sesuai Kemampuan",
        excerpt: "Strategi membangun rumah secara bertahap tanpa mengorbankan estetika dan struktur.",
        category: "Tips & Trik",
        author: "Ari Wibowo",
        authorTitle: "Architecture Expert",
        date: "28 Agu 2023",
        readTime: "7 min baca",
        imageUrl: "https://images.unsplash.com/photo-1448630360428-65456885c650?auto=format&fit=crop&q=80&w=1200",
        authorAvatar: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&q=80&w=150"
    },
    {
        id: 37,
        title: "Kota Mandiri Baru di Barat Jakarta: Potensi Cuan?",
        excerpt: "Menilik prospek investasi di kawasan pengembangan kota mandiri yang sedang masif.",
        category: "Properti Baru",
        author: "Diana Putri",
        authorTitle: "Real Estate Expert",
        date: "25 Agu 2023",
        readTime: "9 min baca",
        imageUrl: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&q=80&w=1200",
        authorAvatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=150"
    },
    {
        id: 38,
        title: "Urban Farming: Berkebun di Lahan Sempit Perkotaan",
        excerpt: "Manfaatkan rooftop atau balkon untuk memenuhi kebutuhan pangan keluarga.",
        category: "Gaya Hidup",
        author: "Sarah Wijaya",
        authorTitle: "Lifestyle Blogger",
        date: "20 Agu 2023",
        readTime: "6 min baca",
        imageUrl: "https://images.unsplash.com/photo-1591857177580-dc82b7ac4e17?auto=format&fit=crop&q=80&w=1200",
        authorAvatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&q=80&w=150"
    },
    {
        id: 39,
        title: "Cara Menilai Kondisi Bangunan Sebelum Membeli Rumah Bekas",
        excerpt: "Checklist penting agar tidak terkecoh dengan renovasi kosmetik pada rumah seken.",
        category: "Tips & Trik",
        author: "Ari Wibowo",
        authorTitle: "Construction Analyst",
        date: "15 Agu 2023",
        readTime: "10 min baca",
        imageUrl: "https://images.unsplash.com/photo-1582268611958-ebfd161ef9cf?auto=format&fit=crop&q=80&w=1200",
        authorAvatar: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&q=80&w=150"
    },
    {
        id: 40,
        title: "Pemanfaatan Roof Garden pada Bangunan Komersial",
        excerpt: "Bagaimana ruang hijau di atap gedung meningkatkan nilai jual dan efisiensi energi.",
        category: "Tren Pasar",
        author: "Diana Putri",
        authorTitle: "Real Estate Expert",
        date: "10 Agu 2023",
        readTime: "7 min baca",
        imageUrl: "https://images.unsplash.com/photo-1590494165264-1ebe3602eb80?auto=format&fit=crop&q=80&w=1200",
        authorAvatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=150"
    },
    {
        id: 41,
        title: "Eksplorasi Arsitektur Tropis Modern di Bali",
        excerpt: "Menilik desain villa yang memadukan kearifan lokal dengan estetika kontemporer.",
        category: "Desain",
        author: "Rendi Pratama",
        authorTitle: "Architecture Writer",
        date: "05 Agu 2023",
        readTime: "8 min baca",
        imageUrl: "https://images.unsplash.com/photo-1537996194471-e657df975ab4?auto=format&fit=crop&q=80&w=1200",
        authorAvatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=150"
    },
    {
        id: 42,
        title: "Tips Memilih Home Theater System untuk Rumah",
        excerpt: "Hadirkan pengalaman menonton bioskop di ruang tamu Anda dengan setup yang tepat.",
        category: "Gaya Hidup",
        author: "Ari Wibowo",
        authorTitle: "AV Specialist",
        date: "01 Agu 2023",
        readTime: "6 min baca",
        imageUrl: "https://images.unsplash.com/photo-1593784991095-a205069470b6?auto=format&fit=crop&q=80&w=1200",
        authorAvatar: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&q=80&w=150"
    },
    {
        id: 43,
        title: "Prosedur Sewa Menyewa Properti untuk Warga Negara Asing",
        excerpt: "Regulasi terbaru mengenai kepemilikan dan hak guna properti bagi WNA di Indonesia.",
        category: "Hukum & Legal",
        author: "Maya Indah",
        authorTitle: "Legal Consultant",
        date: "28 Jul 2023",
        readTime: "7 min baca",
        imageUrl: "https://images.unsplash.com/photo-1450101499163-c8848c66ca85?auto=format&fit=crop&q=80&w=1200",
        authorAvatar: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&q=80&w=150"
    },
    {
        id: 44,
        title: "Review Kawasan Hunian Berbasis TOD di Tangerang",
        excerpt: "Kemudahan akses transportasi menjadi nilai jual utama pengembangan kawasan ini.",
        category: "Properti Baru",
        author: "Diana Putri",
        authorTitle: "Real Estate Expert",
        date: "25 Jul 2023",
        readTime: "8 min baca",
        imageUrl: "https://images.unsplash.com/photo-1503387762-592deb58ef4e?auto=format&fit=crop&q=80&w=1200",
        authorAvatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=150"
    },
    {
        id: 45,
        title: "Cara Cerdas Menggunakan Dana Darurat untuk Perbaikan Rumah",
        excerpt: "Kapan Anda boleh mengambil dana darurat untuk urusan properti dan cara menggantinya.",
        category: "Keuangan",
        author: "Budi Santoso",
        authorTitle: "Financial Planner",
        date: "20 Jul 2023",
        readTime: "6 min baca",
        imageUrl: "https://images.unsplash.com/photo-1554224154-26032ffc0d07?auto=format&fit=crop&q=80&w=1200",
        authorAvatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&q=80&w=150"
    },
    {
        id: 46,
        title: "Tren Desain Kamar Tidur Minimalis ala Hotel Bintang Lima",
        excerpt: "Wujudkan kenyamanan istirahat maksimal dengan sentuhan kemewahan yang elegan.",
        category: "Desain",
        author: "Sarah Wijaya",
        authorTitle: "Interior Designer",
        date: "15 Jul 2023",
        readTime: "6 min baca",
        imageUrl: "https://images.unsplash.com/photo-1540518614846-7eded433c457?auto=format&fit=crop&q=80&w=1200",
        authorAvatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&q=80&w=150"
    },
    {
        id: 47,
        title: "Potensi Kenaikan Harga Properti di Sekitar Jalur LRT Baru",
        excerpt: "Menganalisis data historis kenaikan harga properti di dekat fasilitas transportasi publik.",
        category: "Tren Pasar",
        author: "Diana Putri",
        authorTitle: "Real Estate Expert",
        date: "10 Jul 2023",
        readTime: "7 min baca",
        imageUrl: "https://images.unsplash.com/photo-1519632832544-7729cf301a2f?auto=format&fit=crop&q=80&w=1200",
        authorAvatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=150"
    },
    {
        id: 48,
        title: "Manfaat Memiliki Balkon di Hunian Perkotaan",
        excerpt: "Ruang luar minimalis yang memberikan dampak besar bagi kesehatan dan kenyamanan.",
        category: "Gaya Hidup",
        author: "Sarah Wijaya",
        authorTitle: "Lifestyle Blogger",
        date: "05 Jul 2023",
        readTime: "4 min baca",
        imageUrl: "https://images.unsplash.com/photo-1464373114110-eb76337d63ef?auto=format&fit=crop&q=80&w=1200",
        authorAvatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&q=80&w=150"
    },
    {
        id: 49,
        title: "Panduan Memilih Furniture untuk Rumah dengan Anak Kecil",
        excerpt: "Tips interior yang kids-friendly namun tetap terlihat stylish dan dewasa.",
        category: "Desain",
        author: "Rendi Pratama",
        authorTitle: "Family Design Expert",
        date: "01 Jul 2023",
        readTime: "7 min baca",
        imageUrl: "https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&q=80&w=1200",
        authorAvatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=150"
    },
    {
        id: 50,
        title: "Ekspektasi vs Realita Membangun Rumah Secara Mandiri",
        excerpt: "Kisah suka duka dan pelajaran berharga dari mereka yang berani membangun rumah sendiri.",
        category: "Tips & Trik",
        author: "Ari Wibowo",
        authorTitle: "Project Consultant",
        date: "28 Jun 2023",
        readTime: "10 min baca",
        imageUrl: "https://images.unsplash.com/photo-1541888946425-d81bb19480c5?auto=format&fit=crop&q=80&w=1200",
        authorAvatar: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&q=80&w=150"
    }
];
